### ISSUE TITLE
Configuration should recursively go through the values 

### ISSUE THREAD

**Issue by retro** [feathersjs/feathers-configuration#2]
Something like this doesn't work:

```
{...
  "auth" : {
      github: {
        "clientID": "ENV_VARIABLE_NAME"
        ...
      }
      ...
    }
    ...
  }
  ...
}
```

**Comment by daffl** [comment]
Currently something like

```json
{
  "auth": {
    "facebook": {},
    "github": {}
  }
}
```

Would set `app.get('auth')` to `{ "facebook": {}, "github": {} }` so it would be `app.get('auth').facebook` and `app.get('auth').github`.

It should set `app.get('auth.facebook')` and `app.get('auth.github')` instead?

**Comment by retro** [comment]
I would like to be able to set the value on the leafs from the `.env` file so it should iterate through all of the nested objects

**Comment by daffl** [comment]
Ah sorry, I missed the env part. Good call. I should be able to get to it later today.

**Comment by ekryski** [comment]
:+1: thanks for reporting that @retro
