### ISSUE TITLE
A way to have local override

### ISSUE THREAD

**Issue by lokenmakwana** [feathersjs/feathers-configuration#20]
I see that NODE_ENV.json override is disabled only for development mode. Is there specific reason for that?

It's already checking for file existence, so it will be good if it just override configs from development.json if the file exists.

That will be helpful to have some configs local only by having default.json in version control and development.json ignored.

**Comment by daffl** [comment]
I don't think there was any good reason why it was done this way. Please feel free to submit a pull request with the check removed and if all tests still pass we can make a new release right away.
