### ISSUE TITLE
Make this repo more about managing configuration

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-configuration#24]
As others have mentioned in #8 we should look at using something like [Vault](https://www.vaultproject.io) or making a configuration service. This might be a way to re-purpose feathers-configuration. It should be more for managing config keys and secrets.

feathers-configuration could be a configuration management service that can store data wherever and just has hooks to encrypt/decrypt values. I think we have a couple options here:

1. Create a feathers-vault adapter. Vault can be used to read/write to many different backends like AWS IAM users, SQL DBs, Files System, etc. I would need to investigate further but @slajax might know more. Could be use like this:

    ```js
    const vault = require('feathers-vault');
    app.use('config', vault(options));
    ```

2. Create our own hooks that encrypt and decrypt keys and allow you to CRUD them as well. It's possibly a little more feathersy. Could look something like this:

    ```js
    const service = require('feathers-mongodb');
    const options = {
       Model: db.collection('config')
    };

    app.use('/config', service(options));

    app.service('config').hooks({
      before: {
        create: [encrypt()]
      },
      before: {
         get: [decrypt()]
      }
    });
    ```

Thoughts @feathersjs/core-team?

**Comment by marshallswain** [comment]
Hopefully we can implement both of them, starting with the second option.  Implementing option 2 would would pave the way to making option 1 possible, anyway, and 2 is much more flexible, staying datastore agnostic, which I agree is more inline with the Feathers way of doing business.

Vault has two APIs: CLI and HTTP.  The adapter could assume that Vault is installed on the local machine unless it receives a `url` or `host` in the config.

**Comment by ekryski** [comment]
Cool. Like you mentioned @marshallswain it might make sense to potentially do both but I do like the plan of just using a one of our existing datastores to start with. It provides a lot of security with very little effort on our part (just a couple hooks).

I think we'd likely want to create a separate feathers-vault adapter that is a little more specialized and supports more advanced use cases rather than relying on a central data store to grab config vars.

**Comment by marshallswain** [comment]
Yeah.  I absolutely agree.  The feathers-vault adapter should be its own entity.

**Comment by slajax** [comment]
We could also implement something in the cli:

'$ feathers config set key value --storage vault'

**Comment by ekryski** [comment]
The interface for this vault module looks pretty nice. https://github.com/kr1sp1n/node-vault

**Comment by slajax** [comment]
closing in favour of #26
