### ISSUE TITLE
Why use "NODE_ENV=development" with default.json?

### ISSUE THREAD

**Issue by parnurzeal** [feathersjs/feathers-configuration#33]
My intuition is to have default.json for running locally w/o setting any NODE_ENV.
And to run on DEV environment, we need to do NODE_ENV=development which would use the `config/development.json` instead.

**Comment by marshallswain** [comment]
@parnurzeal can you state more clearly what you think the action item is here?  Should we change something with the generator?  Or is there something specific with this module?

**Comment by daffl** [comment]
`default.json` is the base configuration which will always be used. If `NODE_ENV` is set it will extend `default.json` with `<NODE_ENV>.json` so as you pointed out, with `NODE_ENV=development` the configuration will be `default.json` extended with `development.json` (meaning fields not in `development.json` will be taken from `default.json`).

**Comment by parnurzeal** [comment]
Thanks for the answer. I just realized the package I used is too old that the behavior has already been changed. Previously, the development is default setting.

https://github.com/feathersjs/feathers-configuration/blob/v0.2.3/src/index.js#L48
