### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers-configuration#36]
Docs say:

```
require('feathers-configuration')()
```

I need to do

```
require('feathers-configuration')()()
```

I'd like to do

```
require('feathers-configuration')
```

just like in node-config.

**Comment by ekryski** [comment]
Hmm... `require('feathers-configuration')()` works for me. You still seeing this issue?

**Comment by eddyystop** [comment]
I had a custom node-config wrapper before feathers-configuration, and I really wanted to do just the require, like you.

The only way I found to do it was to module.exports a getter. But you can only do that in ES5. I doubt you can achomplish this in ES6.
