### ISSUE TITLE
Getting Env name

### ISSUE THREAD

**Issue by josx** [feathersjs/feathers-configuration#41]
I think it is usefull to know which enviroment is loaded.
Example for doing something in default or development mode. (not using directly env vars in node).
@daffl  what do you think about?

**Comment by eddyystop** [comment]
What are you needing that `process.env.NODE_ENV` doe not provide?

**Comment by josx** [comment]
Yes, I know that is what i want.
But i think it is usefull to have it the configuration module, so we can do app.get('env') or something like that.

**Comment by eddyystop** [comment]
I'm not sure I get the advantage of `app.get('env') ` over the obvious `process.env.NODE_ENV`.

**Comment by marshallswain** [comment]
You can actually achieve this with the current module.  In your config, do this:

```json
{
  "env": "NODE_ENV"
}
```

That should do the trick.  It will read the NODE_ENV environment variable and make it available at `app.get('env')`

**Comment by josx** [comment]
Ok, will do it this way.
